### ISSUE TITLE
Keyboard.h and Mouse.h, no such file or directory

### ISSUE THREAD

**Issue by celinederoland** [sparkfun/MaKeyMaKey#8]
Hello,

I had an error on line 28 when uploading the file makey_makey.ino in my makey makey card. 
If it happens to someone else, I have been able to solve the problem with removing the includes of Keyboard.h and Mouse.h

Regards,
Céline de Roland

**Comment by jimblom** [comment]
Hi Céline,

We had to add those includes for some of the more recent versions of Arduino. It looks like Arduino 1.6.6 was the first release to make that change.

I've added [a check](https://github.com/sparkfun/MaKeyMaKey/blob/master/firmware/Arduino/makey_makey/makey_makey.ino#L48) to the firmware to avoid including those files if the Arduino version is older.

Thanks for the heads up!
